In [50]:
# a)
import pandas as pd
import numpy as np

dataset = pd.read_csv('pima-indians-diabetes.csv',header=None)
print("shape:",dataset.shape)
print(dataset.head(20))

shape: (768, 9)
     0    1   2   3    4     5      6   7  8
0    6  148  72  35    0  33.6  0.627  50  1
1    1   85  66  29    0  26.6  0.351  31  0
2    8  183  64   0    0  23.3  0.672  32  1
3    1   89  66  23   94  28.1  0.167  21  0
4    0  137  40  35  168  43.1  2.288  33  1
5    5  116  74   0    0  25.6  0.201  30  0
6    3   78  50  32   88  31.0  0.248  26  1
7   10  115   0   0    0  35.3  0.134  29  0
8    2  197  70  45  543  30.5  0.158  53  1
9    8  125  96   0    0   0.0  0.232  54  1
10   4  110  92   0    0  37.6  0.191  30  0
11  10  168  74   0    0  38.0  0.537  34  1
12  10  139  80   0    0  27.1  1.441  57  0
13   1  189  60  23  846  30.1  0.398  59  1
14   5  166  72  19  175  25.8  0.587  51  1
15   7  100   0   0    0  30.0  0.484  32  1
16   0  118  84  47  230  45.8  0.551  31  1
17   7  107  74   0    0  29.6  0.254  31  1
18   1  103  30  38   83  43.3  0.183  33  0
19   1  115  70  30   96  34.6  0.529  32  1


In [51]:
# b)
cell_0_count = len(dataset[dataset[1]==0]) + len(dataset[dataset[2]==0]) + len(dataset[dataset[3]==0]) + len(dataset[dataset[4]==0]) + len(dataset[dataset[5]==0])
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0,np.NaN)
print(dataset.head(20))
print("nan으로 치환된 데이터 셀의 개수 : ",cell_0_count)

     0      1     2     3      4     5      6   7  8
0    6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1    1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2    8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3    1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4    0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
5    5  116.0  74.0   NaN    NaN  25.6  0.201  30  0
6    3   78.0  50.0  32.0   88.0  31.0  0.248  26  1
7   10  115.0   NaN   NaN    NaN  35.3  0.134  29  0
8    2  197.0  70.0  45.0  543.0  30.5  0.158  53  1
9    8  125.0  96.0   NaN    NaN   NaN  0.232  54  1
10   4  110.0  92.0   NaN    NaN  37.6  0.191  30  0
11  10  168.0  74.0   NaN    NaN  38.0  0.537  34  1
12  10  139.0  80.0   NaN    NaN  27.1  1.441  57  0
13   1  189.0  60.0  23.0  846.0  30.1  0.398  59  1
14   5  166.0  72.0  19.0  175.0  25.8  0.587  51  1
15   7  100.0   NaN   NaN    NaN  30.0  0.484  32  1
16   0  118.0  84.0  47.0  230.0  45.8  0.551  31  1
17   7  107.0  74.0   NaN    NaN  29.6  0.254 

In [52]:
# c)
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

dataset = pd.read_csv('pima-indians-diabetes.csv',header=None)
dataset = dataset[0].map(lambda x:"section0" if x==0 else "section1" if x<3 else "section2")
dataset = pd.DataFrame(dataset)
dataset

0
0    section2
1    section1
2    section2
3    section1
4    section0
..        ...
763  section2
764  section1
765  section2
766  section1
767  section1

[768 rows x 1 columns]

In [53]:
le = LabelEncoder()
encoder = OneHotEncoder(categories="auto")
median = len(dataset)//2

le_dataset = dataset.apply(le.fit_transform)
print(le_dataset[median-10:median+10])
print(type(le_dataset))



     0
374  1
375  2
376  0
377  1
378  2
379  0
380  1
381  0
382  1
383  1
384  1
385  1
386  2
387  2
388  2
389  2
390  1
391  2
392  1
393  2
<class 'pandas.core.frame.DataFrame'>


In [54]:
oh_dataset = encoder.fit_transform(le_dataset)
print(oh_dataset[median-10:median+10])
print(type(oh_dataset))

oh_dataset = oh_dataset.toarray()
print(oh_dataset[median-10:median+10])
print(type(oh_dataset))


  (0, 1)	1.0
  (1, 2)	1.0
  (2, 0)	1.0
  (3, 1)	1.0
  (4, 2)	1.0
  (5, 0)	1.0
  (6, 1)	1.0
  (7, 0)	1.0
  (8, 1)	1.0
  (9, 1)	1.0
  (10, 1)	1.0
  (11, 1)	1.0
  (12, 2)	1.0
  (13, 2)	1.0
  (14, 2)	1.0
  (15, 2)	1.0
  (16, 1)	1.0
  (17, 2)	1.0
  (18, 1)	1.0
  (19, 2)	1.0
<class 'scipy.sparse._csr.csr_matrix'>
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>


In [55]:
# d)
dataset = pd.read_csv('pima-indians-diabetes.csv',header=None)
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0,np.NaN)
print("삭제 전")
print(dataset.shape)

dataset.dropna(inplace=True)
print("삭제 후")
print(dataset.shape)



삭제 전
(768, 9)
삭제 후
(392, 9)


In [56]:
# e)
dataset = pd.read_csv('pima-indians-diabetes.csv',header=None)
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0,np.NaN)

replace_index = set()

for column in dataset.columns:
    mean = dataset[column].mean()
    for index, row in enumerate(dataset[column]):
        if pd.isna(row):
            replace_index.add(index)
            dataset.loc[index,column] = mean
    
print("치환된 행")
print(dataset.loc[list(replace_index)])
print("치환된 행의 개수 : ",len(replace_index) )


치환된 행
      0      1          2         3           4     5      6   7  8
0     6  148.0  72.000000  35.00000  155.548223  33.6  0.627  50  1
1     1   85.0  66.000000  29.00000  155.548223  26.6  0.351  31  0
2     8  183.0  64.000000  29.15342  155.548223  23.3  0.672  32  1
5     5  116.0  74.000000  29.15342  155.548223  25.6  0.201  30  0
7    10  115.0  72.405184  29.15342  155.548223  35.3  0.134  29  0
..   ..    ...        ...       ...         ...   ...    ...  .. ..
761   9  170.0  74.000000  31.00000  155.548223  44.0  0.403  43  1
762   9   89.0  62.000000  29.15342  155.548223  22.5  0.142  33  0
764   2  122.0  70.000000  27.00000  155.548223  36.8  0.340  27  0
766   1  126.0  60.000000  29.15342  155.548223  30.1  0.349  47  1
767   1   93.0  70.000000  31.00000  155.548223  30.4  0.315  23  0

[376 rows x 9 columns]
치환된 행의 개수 :  376


In [57]:
# f)
import csv
dataset2 = dataset.copy()

isp = dataset2[8] == 1
isn = dataset2[8] == 0
p_dataset = dataset2[isp]
n_dataset = dataset2[isn]

train_p =  p_dataset.sample(n=50,replace=False)
train_p_index = train_p.index
p_dataset = p_dataset.drop(train_p_index)
test_p = p_dataset.sample(n=50,replace=False)
train_n =  n_dataset.sample(n=50,replace=False)
train_n_index = train_n.index
n_dataset = n_dataset.drop(train_n_index)
test_n = n_dataset.sample(n=50,replace=False)

trainset = pd.concat([train_p,train_n], ignore_index=True)
testset = pd.concat([test_p,test_n], ignore_index=True)

trainset.to_csv("trainset.csv",mode='w')
trainset.to_csv("testset.csv",mode="w")
