In [1]:
# a)
import pandas as pd
import numpy as np

dataset = pd.read_csv('pima-indians-diabetes.csv',header=None)
print(dataset.shape)
print(dataset.head(20))

(768, 9)
     0    1   2   3    4     5      6   7  8
0    6  148  72  35    0  33.6  0.627  50  1
1    1   85  66  29    0  26.6  0.351  31  0
2    8  183  64   0    0  23.3  0.672  32  1
3    1   89  66  23   94  28.1  0.167  21  0
4    0  137  40  35  168  43.1  2.288  33  1
5    5  116  74   0    0  25.6  0.201  30  0
6    3   78  50  32   88  31.0  0.248  26  1
7   10  115   0   0    0  35.3  0.134  29  0
8    2  197  70  45  543  30.5  0.158  53  1
9    8  125  96   0    0   0.0  0.232  54  1
10   4  110  92   0    0  37.6  0.191  30  0
11  10  168  74   0    0  38.0  0.537  34  1
12  10  139  80   0    0  27.1  1.441  57  0
13   1  189  60  23  846  30.1  0.398  59  1
14   5  166  72  19  175  25.8  0.587  51  1
15   7  100   0   0    0  30.0  0.484  32  1
16   0  118  84  47  230  45.8  0.551  31  1
17   7  107  74   0    0  29.6  0.254  31  1
18   1  103  30  38   83  43.3  0.183  33  0
19   1  115  70  30   96  34.6  0.529  32  1


In [2]:
# b)
cell_0_count = len(dataset[dataset[1]==0]) + len(dataset[dataset[2]==0]) + len(dataset[dataset[3]==0]) + len(dataset[dataset[4]==0]) + len(dataset[dataset[5]==0])
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0,np.NaN)
print(dataset.head(20))
print("nan으로 치환된 데이터 셀의 개수 : ",cell_0_count)

     0      1     2     3      4     5      6   7  8
0    6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1    1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2    8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3    1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4    0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
5    5  116.0  74.0   NaN    NaN  25.6  0.201  30  0
6    3   78.0  50.0  32.0   88.0  31.0  0.248  26  1
7   10  115.0   NaN   NaN    NaN  35.3  0.134  29  0
8    2  197.0  70.0  45.0  543.0  30.5  0.158  53  1
9    8  125.0  96.0   NaN    NaN   NaN  0.232  54  1
10   4  110.0  92.0   NaN    NaN  37.6  0.191  30  0
11  10  168.0  74.0   NaN    NaN  38.0  0.537  34  1
12  10  139.0  80.0   NaN    NaN  27.1  1.441  57  0
13   1  189.0  60.0  23.0  846.0  30.1  0.398  59  1
14   5  166.0  72.0  19.0  175.0  25.8  0.587  51  1
15   7  100.0   NaN   NaN    NaN  30.0  0.484  32  1
16   0  118.0  84.0  47.0  230.0  45.8  0.551  31  1
17   7  107.0  74.0   NaN    NaN  29.6  0.254 

In [9]:
# c)
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

dataset = pd.read_csv('pima-indians-diabetes.csv',header=None)
dataset[(dataset[0] == 0)] = 0
dataset[(dataset[0] == 1)] = 1
dataset[(dataset[0] == 2)] = 1
dataset[(dataset[0] == 3)] = 1
dataset[(dataset[0] > 3)] = 2
dataset = dataset[0]
dataset = pd.DataFrame(dataset)

encoder = OneHotEncoder(categories="auto")
dataset = encoder.fit_transform(dataset)
print(dataset)
print(type(dataset))

dataset = dataset.toarray()
print(dataset[374:395])
print(type(dataset))

dataset = pd.DataFrame(dataset)
print(dataset[374:395])
print(type(dataset))



  (0, 2)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 1)	1.0
  (4, 0)	1.0
  (5, 2)	1.0
  (6, 1)	1.0
  (7, 2)	1.0
  (8, 1)	1.0
  (9, 2)	1.0
  (10, 2)	1.0
  (11, 2)	1.0
  (12, 2)	1.0
  (13, 1)	1.0
  (14, 2)	1.0
  (15, 2)	1.0
  (16, 0)	1.0
  (17, 2)	1.0
  (18, 1)	1.0
  (19, 1)	1.0
  (20, 1)	1.0
  (21, 2)	1.0
  (22, 2)	1.0
  (23, 2)	1.0
  (24, 2)	1.0
  :	:
  (743, 2)	1.0
  (744, 2)	1.0
  (745, 2)	1.0
  (746, 1)	1.0
  (747, 1)	1.0
  (748, 1)	1.0
  (749, 2)	1.0
  (750, 2)	1.0
  (751, 1)	1.0
  (752, 1)	1.0
  (753, 0)	1.0
  (754, 2)	1.0
  (755, 1)	1.0
  (756, 2)	1.0
  (757, 0)	1.0
  (758, 1)	1.0
  (759, 2)	1.0
  (760, 1)	1.0
  (761, 2)	1.0
  (762, 2)	1.0
  (763, 2)	1.0
  (764, 1)	1.0
  (765, 2)	1.0
  (766, 1)	1.0
  (767, 1)	1.0
<class 'scipy.sparse._csr.csr_matrix'>
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]


In [13]:
# d)
dataset = pd.read_csv('pima-indians-diabetes.csv',header=None)
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0,np.NaN)
print(dataset.shape)

dataset.dropna(inplace=True)
print(dataset.shape)

print("768 -> 392")

(768, 9)
(768, 9)


In [5]:
# e)

In [6]:
# f)